### ISSUE TITLE
torch.cuda.set_device(self.gpus[0])

### ISSUE THREAD

**Issue by ashergaga** [hanzhanggit/StackGAN-v2#23]
RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:32

Please tell me how to solve this problem?

**Comment by michaellee666** [comment]
You might be getting that error if the pre-trained model is trained on a different number of Cuda devices. For example, while training the model you used 3 Cuda devices and now you are loading the same trained model on a device with only a single Cuda device.

**Comment by jdesouza-ai** [comment]
> RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:32
> 
> Please tell me how to solve this problem?

@ashergaga I am also getting the same problem - did you ever resolve this?

**Comment by jdesouza-ai** [comment]
Hi - I just solved this.  When you run the command for evaluation in the docs it says gpu 1 - change this to gpu 0.

python main.py --cfg cfg/eval_birds.yml --gpu 0
